language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 5.5
  include:
    - php: 5.5
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest --prefer-dist"'
    - php: 5.5
      env: 'BOX=yes'
    - php: 5.6
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-source --prefer-highest"'
    - php: 7.0
      env: CHECKS=yes
    - php: hhvm

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then travis_retry composer require satooshi/php-coveralls:dev-master -n ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then travis_retry composer install --dev --prefer-source --prefer-stable --no-interaction -n ; fi
  - travis_retry composer install --dev ${COMPOSER_FLAGS} --no-interaction -n ; fi

install:
  - mkdir -p build/logs
  - mkdir -p build/logs/docs
  - mkdir -p tests/coverage
  - mkdir -p tests/meta
  - mkdir -p tests/logs
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  #- if [ "$CHECKS" = "yes" ]; then travis_retry composer install-devtools ; fi

script:
  - mkdir -p tests/logs
  #- if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then travis_retry vendor/bin/phpunit -c phpunit.hhvm.xml.dist ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]];  then travis_retry vendor/bin/phpunit -c phpunit.xml.dist ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]];  then travis_retry vendor/bin/phpunit --coverage-clover build/logs/clover.xml ; fi
  #- if [ "$CHECKS" = "yes" ]; then composer sca ; fi

after_script:
  #- if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then php vendor/bin/coveralls ; fi
  #- if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/coveralls -v ; fi
  #- if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/phpspec run -v ; fi

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" != '5.6' ]]; then travis_retry php vendor/bin/coveralls -v --exclude-no-stmt ; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then travis_retry php vendor/bin/coveralls -v ; fi
  #- if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php vendor/bin/phpspec run -v ; fi
  - travis_retry php vendor/bin/php-cs-fixer fix --dry-run -vv

branches:
  only:
    - master
